---
apiVersion: v1
kind: Service
metadata:
  name: app-demo2-svc
  namespace: app-demo1
spec:
  selector:
    app: app-demo2
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
